#name = input("Ваше имя")
#print("Привет,", name)
#age = input("Сколько тебе лет Родион?")
#print("Ваш возраст", age)
number = float(input("Введите первое число"))
print("Ваше число", number)
number2 = float(input("Введите второе число"))
print("Ваше число", number)
print("Операции над числами")
print("Сложите эти числа")
print(number+number2)

print("Сложение", number + number2)
print("Вычитание", number - number2)
print("Умножение", number * number2)
print("Деление", number / number2)
